[build]
  base    = "frontend"
  publish = "/build"     # or "frontend/build" for Create React App
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-service.onrender.com/api/:splat"
  status = 200
  force = true

