[build]
  base    = "frontend"
  publish = "dist"             # or "build" — depends on your actual build output
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend.onrender.com/api/:splat"
  status = 200
  force = true

